PRAGMA foreign_keys = ON;
PRAGMA journal_mode = WAL;
PRAGMA busy_timeout = 5000;
CREATE TABLE IF NOT EXISTS users (id INTEGER PRIMARY KEY, username TEXT NOT NULL UNIQUE, password_hash TEXT NOT NULL, created_at INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS tokens (token_hash TEXT PRIMARY KEY, user_id INTEGER NOT NULL REFERENCES users(id), created_at INTEGER NOT NULL, expires_at INTEGER NOT NULL DEFAULT 0);
CREATE TABLE IF NOT EXISTS namespaces (name TEXT PRIMARY KEY, kind TEXT NOT NULL CHECK(kind IN ('user','organization')));
CREATE TABLE IF NOT EXISTS namespace_members (namespace TEXT NOT NULL REFERENCES namespaces(name), user_id INTEGER NOT NULL REFERENCES users(id), role TEXT NOT NULL CHECK(role IN ('admin','write','read')), PRIMARY KEY(namespace,user_id));
CREATE TABLE IF NOT EXISTS repositories (id INTEGER PRIMARY KEY, owner TEXT NOT NULL REFERENCES namespaces(name), name TEXT NOT NULL, description TEXT NOT NULL DEFAULT '', visibility TEXT NOT NULL DEFAULT 'private' CHECK(visibility IN ('private','public')), default_branch TEXT NOT NULL DEFAULT 'main', require_review INTEGER NOT NULL DEFAULT 1, created_at INTEGER NOT NULL, updated_at INTEGER NOT NULL, default_oid TEXT NOT NULL DEFAULT '', UNIQUE(owner,name));
CREATE TABLE IF NOT EXISTS repo_members (repo_id INTEGER NOT NULL REFERENCES repositories(id), user_id INTEGER NOT NULL REFERENCES users(id), role TEXT NOT NULL CHECK(role IN ('admin','write','read')), PRIMARY KEY(repo_id,user_id));
CREATE TABLE IF NOT EXISTS pins (repo_id INTEGER NOT NULL REFERENCES repositories(id), user_id INTEGER NOT NULL REFERENCES users(id), PRIMARY KEY(repo_id,user_id));
CREATE TABLE IF NOT EXISTS groups (id INTEGER PRIMARY KEY, name TEXT NOT NULL, creator_id INTEGER NOT NULL REFERENCES users(id), shared INTEGER NOT NULL DEFAULT 0, created_at INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS group_repos (group_id INTEGER NOT NULL REFERENCES groups(id) ON DELETE CASCADE, repo_id INTEGER NOT NULL REFERENCES repositories(id), PRIMARY KEY(group_id,repo_id));
CREATE TABLE IF NOT EXISTS issues (id INTEGER PRIMARY KEY, repo_id INTEGER NOT NULL REFERENCES repositories(id), author_id INTEGER NOT NULL REFERENCES users(id), title TEXT NOT NULL, body TEXT NOT NULL DEFAULT '', state TEXT NOT NULL DEFAULT 'open' CHECK(state IN ('open','closed')), created_at INTEGER NOT NULL, updated_at INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS pull_requests (id INTEGER PRIMARY KEY, repo_id INTEGER NOT NULL REFERENCES repositories(id), author_id INTEGER NOT NULL REFERENCES users(id), title TEXT NOT NULL, body TEXT NOT NULL DEFAULT '', base_branch TEXT NOT NULL, head_branch TEXT NOT NULL, state TEXT NOT NULL DEFAULT 'open' CHECK(state IN ('open','closed','merged')), created_at INTEGER NOT NULL, updated_at INTEGER NOT NULL, merged_oid TEXT NOT NULL DEFAULT '');
CREATE TABLE IF NOT EXISTS comments (id INTEGER PRIMARY KEY, repo_id INTEGER NOT NULL REFERENCES repositories(id), target_type TEXT NOT NULL CHECK(target_type IN ('issue','pull')), target_id INTEGER NOT NULL, author_id INTEGER NOT NULL REFERENCES users(id), body TEXT NOT NULL, path TEXT NOT NULL DEFAULT '', line INTEGER NOT NULL DEFAULT 0, commit_oid TEXT NOT NULL DEFAULT '', created_at INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS reviews (id INTEGER PRIMARY KEY, pull_id INTEGER NOT NULL REFERENCES pull_requests(id), author_id INTEGER NOT NULL REFERENCES users(id), decision TEXT NOT NULL CHECK(decision IN ('approve','request_changes','comment')), body TEXT NOT NULL DEFAULT '', commit_oid TEXT NOT NULL, created_at INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS ssh_keys (id INTEGER PRIMARY KEY, user_id INTEGER NOT NULL REFERENCES users(id), title TEXT NOT NULL, public_key TEXT NOT NULL UNIQUE, created_at INTEGER NOT NULL);
CREATE INDEX IF NOT EXISTS repositories_freshness ON repositories(updated_at DESC,id);
CREATE INDEX IF NOT EXISTS issues_repo ON issues(repo_id,id);
CREATE INDEX IF NOT EXISTS pulls_repo ON pull_requests(repo_id,id);
CREATE INDEX IF NOT EXISTS comments_target ON comments(target_type,target_id,id);
CREATE INDEX IF NOT EXISTS reviews_pull ON reviews(pull_id,id);
